# Generated by Django 3.2 on 2023-05-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230526_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'DeActive')], default='active', max_length=12),
        ),
    ]
